import marimo

__generated_with = "0.23.14"
app = marimo.App(width="medium")

with app.setup:
    import marimo as mo
    import inspect
    import numpy as np
    import plotly.express as px
    import plotly.graph_objects as go
    import plotly.io as pio
    import polars as pl
    import pymc as pm
    import arviz_plots as azp

    RANDOM_SEED = 42
    PYMC_BLUE = "#154A72"
    PYMC_GREEN = "#81C240"
    PYMC_LIGHT_BLUE = "#4A9EDE"
    PYMC_DARK_GREEN = "#40611F"
    pymc_template = go.layout.Template()
    pymc_template.layout = go.Layout(
        colorway=[
            PYMC_BLUE,
            PYMC_GREEN,
            PYMC_LIGHT_BLUE,
            "#15726C",
            "#C2C240",
            PYMC_DARK_GREEN,
            "#151B72",
            "#40C240",
        ],
        font=dict(color="#333"),
        title=dict(font=dict(color=PYMC_BLUE)),
    )
    pio.templates["course"] = pymc_template
    pio.templates.default = "plotly_white+course"


@app.cell(hide_code=True)
def header():
    mo.md(r"""
    # Session 2.2: Building Models with PyMC

    In this session, we'll continue exploring PyMC by building probabilistic models, specifying priors, and working with deterministic and observed variables.
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Building Models in PyMC

    Now that we understand the basic building blocks of PyMC models, let's see how to combine them to build a complete model. Let's see if we can implement the rat toxicity model from the previous section!

    Recall our dataset:
    """)
    return


@app.cell
def _():
    dose_1 = np.array([-0.86, -0.3, -0.05, 0.73])
    n_1 = 5
    deaths_1 = np.array([0, 1, 3, 5])
    return deaths_1, dose_1, n_1


@app.cell(hide_code=True)
def _():
    mo.vstack(
        [
            mo.md(r"""
    In this dataset `log_dose` includes 4 levels of dosage, on the log scale, each administered to `n=5` rats during the experiment. The response variable is `deaths`, the number of positive responses to the dosage.

    The number of deaths can be modeled as a binomial response, with the probability of death being a linear function of dose:

    $$
    \begin{aligned}
    \text{logit}(p_i) &= \beta_0 + \beta_1 x_i \\
    y_i &\sim \text{Bin}(n_i, p_i) \\
    \end{aligned}
    $$

    Our research interest is in estimating the **LD50**, the dose at which 50% of the rats die.
    """),
            mo.callout(
                mo.md(r"""
    **Exercise:** How do we calculate the LD50 from the model?
    """),
                kind="info",
            ),
        ]
    )
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Prior Specification

    The first step in specifying a PyMC model is defining the prior distributions for each unknown parameter.

    - what are the unknown parameters?
    - which distributions should we use to characterize our beliefs about their values?
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    We need priors for the regression coefficients. We begin with a named
    dimension so the intercept and slope remain identifiable in the model output:
    """)
    return


@app.cell
def _():
    with pm.Model(coords=dict(coeffs=["intercept", "slope"])) as dose_model:
        beta_2 = pm.Normal("beta", mu=0, sigma=10, dims="coeffs")
    dose_model
    return beta_2, dose_model


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Deterministic Variables

    A deterministic variable is one whose values are **completely determined** by the values of their parents.

    In our model, the probability of death is a deterministic function of the dose and the parameters of the model.
    """)
    return


@app.cell
def _(beta_2, dose_1, dose_model):
    with dose_model:
        p = pm.math.invlogit(beta_2[0] + beta_2[1] * dose_1)
    return (p,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    There are two types of deterministic variables in PyMC:

    #### Anonymous deterministic variables

    The easiest way to create a deterministic variable is to operate on or transform one or more variables in a model directly, as we have done above for `p`.

    These are called *anonymous* variables because they are not named variables, as we did for `beta` above. We simply specified the variable as a Python (or PyTensor) expression. This is therefore the simplest way to construct a deterministic variable. The only caveat is that the values generated by anonymous deterministics are not recorded to the model output during model fitting. So, this approach is only appropriate for intermediate values in your model that you do not wish to obtain posterior estimates for, alongside the other variables in the model.

    #### Named deterministic variables

    To ensure that deterministic variables' values are accumulated during sampling, they should be instantiated using the **named deterministic** interface; this uses the `Deterministic` function to create the variable. Two things happen when a variable is created this way:

    1. The variable is given a name (passed as the first argument)
    2. The variable is appended to the model's list of random variables, which ensures that its values are tallied.

    Where does that expression come from? At the LD50, half the subjects die:
    $p = 0.5$, so $\text{logit}(p) = \log(0.5/0.5) = 0$. Setting the linear
    predictor to zero, $\beta_0 + \beta_1 x = 0$, and solving gives
    $x = -\beta_0/\beta_1$. In the model below the two coefficients live in one vector, so this becomes `-beta_2[0] / beta_2[1]`.

    Since we are interested in estimating LD50, let's create a named deterministic variable for it:
    """)
    return


@app.cell
def _(beta_2, dose_model):
    with dose_model:
        pm.Deterministic("ld50", -beta_2[0] / beta_2[1])
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Observed Random Variables

    Stochastic random variables whose values are observed are represented by a different class than unobserved random variables. An `ObservedRV` object is instantiated any time a stochastic variable is specified with data passed as the `observed` argument.

    In our model, the observed rat deaths are represented by an `ObservedRV` using a binomial random variable.
    """)
    return


@app.cell
def _(deaths_1, dose_model, n_1, p):
    with dose_model:
        y_2 = pm.Binomial("y", n=n_1, p=p, observed=deaths_1)
    dose_model
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Factor Potentials

    For some applications, we want to be able to modify the joint density by incorporating terms that don't correspond to probabilities of variables conditional on parents. For example, suppose in our model we want to constrain the slope to be positive, so that the joint density becomes:

    $$p(y,\beta) \propto p(y|\beta) p(\beta) I(\beta \gt 0)$$

    We call such log-probability terms **factor potentials** (Jordan 2004). Bayesian
    hierarchical notation does not accommodate these potentials.

    ### Creation of Potentials

    A potential can be created via the `Potential` function, in a way very similar to `Deterministic`'s named interface:
    """)
    return


@app.cell
def _(beta_2, dose_model):
    with dose_model:
        pm.Potential("slope_constraint", pm.math.switch(beta_2[1] < 0, -np.inf, 0))
    return




@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Our model specification is complete! Let's take a look at the model structure:
    """)
    return


@app.cell
def _(dose_model):
    dose_model
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Exercise: Alternative Model Specification

    The use of a `Potential` to constrain the slope to be positive is not a great solution. A better approach is to use a prior distribution that is constrained to be positive.

    Try re-specifying the model using this strategy.
    """)
    return


@app.cell
def _(deaths_1, dose_1, n_1):
    def exercise_positive_slope_model():
        with pm.Model() as model:
            # YOUR CODE HERE — Normal prior for the intercept, and a
            # positive-constrained prior for the slope (no Potential needed)
            beta0 = ...
            beta1 = ...
            p = pm.math.invlogit(beta0 + beta1 * dose_1)
            pm.Deterministic("ld50", -beta0 / beta1)
            pm.Binomial("y", n=n_1, p=p, observed=deaths_1)
        return model

    return (exercise_positive_slope_model,)


@app.cell(hide_code=True)
def _():
    mo.accordion(
        {
            "Hint": mo.md(
                "Positive-valued distributions include `HalfNormal`, `LogNormal`, and `Gamma`."
            ),
        }
    )
    return


@app.cell(hide_code=True)
def _():
    run_positive_slope = mo.ui.run_button(label="▶ Run exercise")
    run_positive_slope
    return (run_positive_slope,)


@app.cell(hide_code=True)
def _(exercise_positive_slope_model, run_positive_slope):
    mo.stop(
        not run_positive_slope.value,
        mo.md("*Click ▶ Run exercise once your code is ready.*"),
    )
    exercise_positive_slope_model()
    return


@app.cell(hide_code=True)
def _(deaths_1, dose_1, n_1):
    def solution_positive_slope_model():
        with pm.Model() as model:
            beta0 = pm.Normal("beta0", 0, sigma=1)
            beta1 = pm.LogNormal("beta1", 0, sigma=1)
            p = pm.math.invlogit(beta0 + beta1 * dose_1)
            pm.Deterministic("ld50", -beta0 / beta1)
            pm.Binomial("y", n=n_1, p=p, observed=deaths_1)
        return model

    dose_model_4 = solution_positive_slope_model()

    mo.accordion(
        {
            "Solution": mo.vstack(
                [
                    mo.md(
                        f"```python\n{inspect.getsource(solution_positive_slope_model)}\n```"
                    ),
                    dose_model_4,
                    mo.md(
                        "_This model (`dose_model_4`) is used by the cells that follow, so the rest of the notebook works whether or not you complete the exercise._"
                    ),
                ]
            ),
        }
    )
    return (dose_model_4,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Parameter Transformation

    To support efficient sampling by PyMC's MCMC algorithms, any continuous variables that are **constrained** to a sub-interval of the real line are **automatically transformed** so that their support is unconstrained. This frees sampling algorithms from having to deal with boundary constraints.

    For example, if we look at the variables we have created in the model so far:
    """)
    return


@app.cell
def _(dose_model_4):
    _output = mo.md(f"""
    `{dose_model_4.value_vars}`
    """)
    _output
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    The model's `value_vars` attribute stores the values of each random variable actually used by the model's log-likelihood.

    As the name suggests, the variable `beta1` has been log-transformed, and this is the space over which posterior sampling takes place. When a sample is drawn, the value of the transformed variable is simply back-transformed to recover the original variable.

    By default, auto-transformed variables are ignored when summarizing and plotting model output, since they are not generally of interest to the user.
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Prior Predictive Checks

    Before we go ahead and estimate the model parameters from the data, it's a good idea to perform a prior predictive check. This involves sampling from the model before data are incorporated, and gives you an idea of the range of observations that would be considered reasonable within the scope of the modeling assumptions (including choice of priors). If the simulations generate too many extreme observations relative to our expectations based on domain knowledge, then it can be an indication of problems with model formulation.
    """)
    return


@app.cell
def _(dose_model_4):
    with dose_model_4:
        prior_sample = pm.sample_prior_predictive(1000)
    prior_sample
    return (prior_sample,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Let's see what our simulated datasets look like:
    """)
    return


@app.cell
def _(prior_sample):
    azp.plot_dist(prior_sample, group="prior_predictive", var_names=["y"])
    return

@app.cell(hide_code=True)
def _(dose_1, prior_sample):
    prior_probability_largest_dose = (
        1
        / (
            1
            + np.exp(
                -(
                    prior_sample["prior"]["beta0"].values
                    + prior_sample["prior"]["beta1"].values * dose_1[-1]
                )
            )
        )
    ).mean()
    mo.md(
        f"At the largest observed dose, the prior mean death probability is "
        f"`{prior_probability_largest_dose:.3f}`. This is a **prior** model "
        "implication, not a posterior prediction or an observed death rate."
    )
    return (prior_probability_largest_dose,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    How do we interpret this?

    The prior predictive shows deaths relatively uniformly distributed from 0 to 5. This is reasonable since we haven't yet incorporated information about the dose-response relationship. The lack of extreme concentration at any particular value suggests our priors aren't overly informative.
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    If we are happy with our model specification, we can go ahead and estimate the model.
    """)
    return


@app.cell
def _(dose_model_4):
    with dose_model_4:
        trace = pm.sample(random_seed=RANDOM_SEED)
    trace
    return (trace,)


@app.cell
def _(trace):
    azp.plot_dist(trace, var_names=["beta0", "beta1", "ld50"])
    return




@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Prediction on new data

    We might also be interested in predicting at new doses. For example, how many deaths would we expect if we administered the LD50 dose?

    In PyMC, `pm.Data` defines a symbolic data node that we can later replace for prediction.
    """)
    return


@app.cell
def _(dose_1):
    with pm.Model(coords={"doses": ["first", "second", "third", "fourth"]}) as dose_model_5:
        dose_level = pm.Data("dose_level", dose_1, dims="doses")
    return dose_level, dose_model_5


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    The `doses` coordinate labels the dose axis. This prediction model uses a
    no-intercept parameterization with a positive slope:
    $p = \operatorname{logit}^{-1}(\beta_1 x - \beta_0)$. Under this model,
    the 50% dose is `beta0 / beta1` because `beta1 > 0`; that ratio is not an
    LD50 formula for arbitrary parameterizations.
    """)
    return


@app.cell
def _(dose_model_5):
    with dose_model_5:
        beta0 = pm.HalfNormal("beta0", sigma=1)
        beta1 = pm.HalfNormal("beta1", sigma=10)
    return beta0, beta1


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    We use the observed death counts for fitting, then replace only the dose
    data when generating predictions.
    """)
    return


@app.cell
def _(beta0, beta1, deaths_1, dose_level, dose_model_5, n_1):
    with dose_model_5:
        p_4 = pm.Deterministic(
            "p", pm.math.invlogit(beta1 * dose_level - beta0), dims="doses"
        )
        pm.Deterministic("ld50", beta0 / beta1)
        pm.Binomial("y", n=n_1, p=p_4, observed=deaths_1)
    return (p_4,)


@app.cell
def _(dose_model_5):
    dose_model_5
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Now, we estimate the model:
    """)
    return


@app.cell
def _(dose_model_5):
    with dose_model_5:
        trace_1 = pm.sample(random_seed=RANDOM_SEED)
    trace_1
    return (trace_1,)

@app.cell
def _(dose_model_5, n_1, p_4, trace_1):
    with dose_model_5:
        future_deaths = pm.Binomial(
            "future_deaths", n=n_1, p=p_4, dims="doses"
        )
    return (future_deaths,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    For our prediction, we want to pass the LD50 dose to the model. We will just take the mean of the posterior samples for the LD50.
    """)
    return


@app.cell
def _(trace_1):
    trace_1["posterior"]["ld50"].values.mean()
    return


@app.cell(hide_code=True)
def _():
    mo.md("""Swapping data is done with `pm.set_data`. Then, we sample from the
**posterior predictive distribution** by calling `pm.sample_posterior_predictive`.
This samples data from the model using the fitted parameters and the new dose values.""")
    return


@app.cell
def _(dose_model_5, future_deaths, trace_1):
    with dose_model_5:
        pm.set_data(
            {"dose_level": [trace_1["posterior"]["ld50"].values.mean()]},
            coords={"doses": ["ld50"]},
        )
        predictive_samples = pm.sample_posterior_predictive(
            trace_1, var_names=["future_deaths", "p"]
        )
    predictive_samples
    return (predictive_samples,)


@app.cell
def _(predictive_samples):
    def plot_ld50_predictive():
        future_deaths = predictive_samples["posterior_predictive"][
            "future_deaths"
        ].values.flatten()
        fig = go.Figure(go.Histogram(x=future_deaths, histnorm="probability"))
        fig.update_layout(
            xaxis_title="Future Deaths (out of 5)",
            yaxis_title="Probability",
            title="Posterior Predictive: Future Deaths at LD50 Dose",
            xaxis=dict(dtick=1),
        )
        return fig

    plot_ld50_predictive()
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Or, we can generate predictions across a range of doses to see how the probability of death changes with dose.
    """)
    return


@app.cell
def _(dose_model_5, future_deaths, trace_1):
    dose_grid = np.linspace(-1, 1, 200)
    with dose_model_5:
        pm.set_data(
            {"dose_level": dose_grid},
            coords={"doses": [f"d{i}" for i in range(1, 201)]},
        )
        predictive_samples_1 = pm.sample_posterior_predictive(
            trace_1, var_names=["future_deaths", "p"]
        )
    predictive_samples_1
    return dose_grid, predictive_samples_1


@app.cell(hide_code=True)
def _(deaths_1, dose_1, dose_grid, n_1, predictive_samples_1):
    def plot_predictive_dose_response():
        p_samples = predictive_samples_1["posterior_predictive"]["p"].values
        dose_range = dose_grid
        flat_p = p_samples.reshape(-1, p_samples.shape[-1])

        lower_prob, upper_prob = np.quantile(flat_p, [0.055, 0.945], axis=0)
        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=dose_range,
                y=lower_prob,
                mode="lines",
                line=dict(width=0),
                showlegend=False,
            )
        )
        fig.add_trace(
            go.Scatter(
                x=dose_range,
                y=upper_prob,
                mode="lines",
                fill="tonexty",
                fillcolor="rgba(21, 74, 114, 0.2)",
                line=dict(width=0),
                name="89% posterior interval",
            )
        )
        mean_prob = flat_p.mean(axis=0)
        fig.add_trace(
            go.Scatter(
                x=dose_range,
                y=mean_prob,
                mode="lines",
                line=dict(color="rgb(21, 74, 114)", width=3),
                name="Mean",
            )
        )
        empirical_p = deaths_1 / n_1
        fig.add_trace(
            go.Scatter(
                x=dose_1,
                y=empirical_p,
                mode="markers",
                marker=dict(color="red", size=8),
                name="Observed Data",
            )
        )
        fig.update_layout(xaxis_title="Log Dose", yaxis_title="Probability of Death")
        return fig

    plot_predictive_dose_response()
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Exercise: Smart Drug Clinical Trial

    Now that we have a flavor for how PyMC models are specified, let's try building a more complex model.

    We will use a fictitious example from Kruschke (2013) concerning the evaluation of a clinical trial for drug efficacy. The trial aims to evaluate whether a "smart drug" increases intelligence by comparing IQ scores of individuals in a treatment arm (those receiving the drug) to those in a control arm (those receiving a placebo). There are 47 individuals and 42 individuals in the treatment and control arms, respectively.

    Build a model to evaluate the evidence for the drug's effectiveness.

    The data are available in two variables prepared below: `iq`, an array of all
    89 IQ scores, and `group_id`, an integer indicator for each score
    (0 = drug, 1 = placebo).
    """)
    return


@app.cell
def _():
    # fmt: off
    drug_iq_scores = (
        101, 100, 102, 104, 102, 97, 105, 105, 98, 101, 100, 123, 105,
        103, 100, 95, 102, 106, 109, 102, 82, 102, 100, 102, 102, 101,
        102, 102, 103, 103, 97, 97, 103, 101, 97, 104, 96, 103, 124, 101,
        101, 100, 101, 101, 104, 100, 101
    )
    placebo_iq_scores = (
        99, 101, 100, 101, 102, 100, 97, 101, 104, 101, 102, 102, 100,
        105, 88, 101, 100, 104, 100, 100, 100, 101, 102, 103, 97, 101,
        101, 100, 101, 99, 101, 100, 100, 101, 100, 99, 101, 100, 102,
        99, 100, 99
    )
    # fmt: on

    drug = pl.DataFrame(dict(iq=drug_iq_scores, group="drug"))
    placebo = pl.DataFrame(dict(iq=placebo_iq_scores, group="placebo"))
    n1 = len(drug)
    n0 = len(placebo)
    trial_data = pl.concat([drug, placebo])

    iq = trial_data.select("iq").to_numpy().squeeze()
    group_id = (
        trial_data["group"].cast(pl.Categorical).to_physical().to_numpy().squeeze()
    )
    trial_data
    return group_id, iq, trial_data


@app.cell(hide_code=True)
def _(trial_data):
    def plot_iq_histogram():
        fig = px.histogram(
            trial_data,
            x="iq",
            color="group",
            barmode="overlay",
            histnorm="percent",
            labels={"iq": "IQ Score", "group": "Group"},
            title="Distribution of IQ Scores by Group",
            color_discrete_map={"drug": "#636EFA", "placebo": "#EF553B"},
        )
        fig.update_layout(
            legend_title_text="",
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
            ),
            xaxis_title="IQ Score",
            yaxis_title="Percentage",
        )
        return fig


    plot_iq_histogram()
    return


@app.cell
def _(group_id, iq):
    def exercise_drug_model():
        drug_iq = iq[group_id == 0]
        placebo_iq = iq[group_id == 1]

        with pm.Model() as model:
            # YOUR CODE HERE — priors for each group's mean and a shared sigma
            # YOUR CODE HERE — likelihoods for drug_iq and placebo_iq
            # YOUR CODE HERE — an effect_size Deterministic (difference of means)
            ...
        return model

    return (exercise_drug_model,)


@app.cell(hide_code=True)
def _():
    mo.accordion(
        {
            "Hint": mo.md(
                "We are interested in the expected difference in IQ between the treatment and control groups."
            ),
        }
    )
    return


@app.cell(hide_code=True)
def _():
    run_drug_model = mo.ui.run_button(label="▶ Run exercise")
    run_drug_model
    return (run_drug_model,)


@app.cell(hide_code=True)
def _(exercise_drug_model, run_drug_model):
    mo.stop(
        not run_drug_model.value,
        mo.md("*Click ▶ Run exercise once your code is ready.*"),
    )
    exercise_drug_model()
    return


@app.cell(hide_code=True)
def _(group_id, iq):
    def solution_trial_model():
        with pm.Model() as model:
            mu_drug = pm.Normal("mu_drug", 100, sigma=10)
            mu_placebo = pm.Normal("mu_placebo", 100, sigma=10)
            sigma = pm.HalfNormal("sigma", 10)
            pm.Normal("iq_drug", mu=mu_drug, sigma=sigma, observed=iq[group_id == 0])
            pm.Normal(
                "iq_placebo", mu=mu_placebo, sigma=sigma, observed=iq[group_id == 1]
            )
            pm.Deterministic("effect_size", mu_drug - mu_placebo)
        return model

    def extension_best_model():
        with pm.Model(coords=dict(group=["drug", "placebo"])) as model:
            mu = pm.Normal("mu", 100, sigma=10, dims="group")
            sigma = pm.Uniform("sigma", lower=0, upper=20, dims="group")
            nu = pm.Exponential("nu_minus_one", 1 / 30) + 1
            pm.StudentT(
                "like", nu=nu, mu=mu[group_id], sigma=sigma[group_id], observed=iq
            )
            pm.Deterministic("effect_size", mu[0] - mu[1])
        return model

    mo.accordion(
        {
            "Solution": mo.vstack(
                [
                    mo.md(f"```python\n{inspect.getsource(solution_trial_model)}\n```"),
                    mo.lazy(
                        lambda: solution_trial_model(),
                        show_loading_indicator=True,
                    ),
                ]
            ),
            "Extension: a robust BEST model": mo.vstack(
                [
                    mo.md(
                        "Kruschke's *Bayesian Estimation Supersedes the t-test* "
                        "(BEST) model makes two upgrades you will meet properly in "
                        "later sessions. First, instead of separate `mu_drug` / "
                        "`mu_placebo` variables it declares one vector `mu` with "
                        '`dims="group"` and picks each observation\'s mean by '
                        "**indexing with the group array**: `mu[group_id]`, the "
                        "core trick behind the hierarchical models of Session 4.2. "
                        "Second, it swaps the Normal likelihood for a **StudentT** "
                        "whose degrees of freedom `nu` are learned from the data "
                        "(`pm.Exponential(1/30) + 1` shifts the prior so `nu > 1`), "
                        "making the comparison robust to outliers like the two "
                        "IQ scores above 120."
                    ),
                    mo.md(f"```python\n{inspect.getsource(extension_best_model)}\n```"),
                    mo.lazy(
                        lambda: extension_best_model(),
                        show_loading_indicator=True,
                    ),
                ]
            ),
        }
    )
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Session recap

    You constructed PyMC models with named variables, deterministic quantities,
    observed likelihoods, and constrained priors; checked the model with prior
    predictive simulation; fit a posterior; and generated posterior predictions
    after replacing dose data. Session 3.1 turns to the sampler mechanics and
    convergence diagnostics that make those posterior draws trustworthy.
    """)
    return


if __name__ == "__main__":
    app.run()
